"""empty message

Revision ID: 854ae440df5c
Revises: bf835079be0d
Create Date: 2020-09-02 12:00:31.192980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '854ae440df5c'
down_revision = 'bf835079be0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'admin')
    # ### end Alembic commands ###
